#!/bin/bash

MSG="$(cat $1)"
PATTERN="#[0-9]*"

if [[ $MSG =~ $PATTERN ]];then
        echo "Commit de acordo com as diretrizes estabelecidas!"
else
        echo "Commit não possui número de issue!"
        exit 1
fi
